export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const DESCARGA_DATOS_USUARIO_EXITO = 'DESCARGA_DATOS_USUARIO_EXITO'
export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';
export const EDITAR_DATOS_USUARIO_EXITO = 'EDITAR_DATOS_USUARIO_EXITO';
export const  OBTENER_AVATAR_EXITO = ' OBTENER_AVATAR_EXITO';
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'