// se utilizan el en action y en el reducer
//* AYUDAN A DESCRIBIR LO QUE PASA EN LA APP


export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';


export const VER_PRODUCTO = 'VER_PRODUCTO';
export const VER_PRODUCTO_EXITO = 'VER_PRODUCTO_EXITO';
export const VER_PRODUCTO_ERROR = 'VER_PRODUCTO_ERROR';