// se utilizan el en action y en el reducer
//* AYUDAN A DESCRIBIR LO QUE PASA EN LA APP

export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS_USER = 'COMENZAR_DESCARGA_PRODUCTOS_USER ';
export const DESCARGA_PRODUCTOS_USER_EXITO = 'DESCARGA_PRODUCTOS_USER_EXITO';
export const DESCARGA_PRODUCTOS_USER_ERROR = 'DESCARGA_PRODUCTOS_USER_ERROR';

export const VER_PRODUCTO_ID = 'VER_PRODUCTO_ID';
export const VER_PRODUCTO_EXITO_ID = 'VER_PRODUCTO_EXITO_ID';
export const VER_PRODUCTO_ERROR_ID = 'VER_PRODUCTO_ERROR_ID';


export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR'
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO'
export const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO'
export const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR'
export const OBTENER_PRODUCTO_EDICION = 'OBTENER_PRODUCTO_EDICION'



export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR'
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO'
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR'

export const OBTENER_CATEGORIA_EXITO = "OBTENER_CATEGORIA_EXITO";


 export const DESCARGA_PAGINAS_EXITO = "DESCARGA_PAGINAS_EXITO";
 export const DESCARGA_PAGINAS_USER_EXITO = "DESCARGA_PAGINAS_USER_EXITO";

 export const OBTENER_PAGINA_ACTUAL = "OBTENER_PAGINA_ACTUAL";
// export const LOGIN_FAIL = "LOGIN_FAIL";
// export const LOGOUT = "LOGOUT";

// export const SET_MESSAGE = "SET_MESSAGE";
// export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULATAR_ALERTA'

export const DESCARGA_PRODUCTOS_AUTHOR_EXITO = 'DESCARGA_PRODUCTOS_AUTHOR_EXITO'